apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`harbor.apps.house.simonellistonball.com`)
      services:
        - name: harbor
          port: 80
  tls:
    secretName: harbor-tls
