apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redpanda-console
  namespace: redpanda
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`redpanda.apps.house.simonellistonball.com`)
      services:
        - name: redpanda-console
          port: 8080
  tls:
    secretName: redpanda-console-tls
