apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dagster
  namespace: dagster
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dagster.apps.house.simonellistonball.com`)
      services:
        - name: dagster-dagster-webserver
          port: 80
  tls:
    secretName: dagster-tls
