apiVersion: v1
items:
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"litellm","namespace":"ai"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`llm.apps.house.simonellistonball.com`)","services":[{"name":"litellm","port":4000}]}],"tls":{"secretName":"ai-tls"}}}
    creationTimestamp: "2025-12-21T14:12:08Z"
    generation: 1
    name: litellm
    namespace: ai
    resourceVersion: "58442"
    uid: 2ffcfce9-44c4-411f-837d-684015578364
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`llm.apps.house.simonellistonball.com`)
      services:
      - name: litellm
        port: 4000
    tls:
      secretName: ai-tls
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"dagster","namespace":"dagster"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`dagster.apps.house.simonellistonball.com`)","services":[{"name":"dagster-dagster-webserver","port":80}]}],"tls":{"secretName":"dagster-tls"}}}
    creationTimestamp: "2025-12-22T16:08:01Z"
    generation: 1
    name: dagster
    namespace: dagster
    resourceVersion: "169976"
    uid: 332a2cd3-4e8a-43a3-b938-9c25afa0fc8e
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`dagster.apps.house.simonellistonball.com`)
      services:
      - name: dagster-dagster-webserver
        port: 80
    tls:
      secretName: dagster-tls
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"test-web","namespace":"default"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`test.apps.house.simonellistonball.com`)","services":[{"name":"test-web","port":80}]}],"tls":{"secretName":"test-tls"}}}
    creationTimestamp: "2025-12-23T17:55:38Z"
    generation: 1
    name: test-web
    namespace: default
    resourceVersion: "355822"
    uid: f84e7c75-cb56-4bc8-9f20-ad2af689d7c3
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`test.apps.house.simonellistonball.com`)
      services:
      - name: test-web
        port: 80
    tls:
      secretName: test-tls
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"frigate","namespace":"frigate"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(\\`frigate.apps.house.simonellistonball.com\\`)","services":[{"name":"frigate","port":5000}]}],"tls":{"secretName":"frigate-tls"}}}
    creationTimestamp: "2025-12-22T01:57:40Z"
    generation: 1
    name: frigate
    namespace: frigate
    resourceVersion: "103793"
    uid: c860c5c0-00bd-46a7-9297-0e08c624ec56
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(\`frigate.apps.house.simonellistonball.com\`)
      services:
      - name: frigate
        port: 5000
    tls:
      secretName: frigate-tls
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"gitea","namespace":"gitea"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`gitea.apps.house.simonellistonball.com`)","services":[{"name":"gitea-http","port":3000}]}],"tls":{"secretName":"gitea-tls"}}}
    creationTimestamp: "2025-12-22T18:45:20Z"
    generation: 1
    name: gitea
    namespace: gitea
    resourceVersion: "186989"
    uid: 292e7f34-793a-433f-8107-e36e4d2df676
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`gitea.apps.house.simonellistonball.com`)
      services:
      - name: gitea-http
        port: 3000
    tls:
      secretName: gitea-tls
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"harbor","namespace":"harbor"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`harbor.apps.house.simonellistonball.com`)","services":[{"name":"harbor","port":80}]}],"tls":{"secretName":"harbor-tls"}}}
    creationTimestamp: "2025-12-22T13:26:52Z"
    generation: 3
    name: harbor
    namespace: harbor
    resourceVersion: "154169"
    uid: 88ab1a8e-2bf9-4008-a55a-3a3b15249880
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`harbor.apps.house.simonellistonball.com`)
      services:
      - name: harbor
        port: 80
    tls:
      secretName: harbor-tls
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"alertmanager","namespace":"monitoring"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`alertmanager.apps.house.simonellistonball.com`)","services":[{"name":"prometheus-kube-prometheus-alertmanager","port":9093}]}],"tls":{"secretName":"monitoring-tls"}}}
    creationTimestamp: "2025-12-21T04:35:44Z"
    generation: 1
    name: alertmanager
    namespace: monitoring
    resourceVersion: "20591"
    uid: dea08563-3b4e-4d57-a284-b8ee3e190acb
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`alertmanager.apps.house.simonellistonball.com`)
      services:
      - name: prometheus-kube-prometheus-alertmanager
        port: 9093
    tls:
      secretName: monitoring-tls
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"grafana","namespace":"monitoring"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`grafana.apps.house.simonellistonball.com`)","services":[{"name":"prometheus-grafana","port":80}]}],"tls":{"secretName":"monitoring-tls"}}}
    creationTimestamp: "2025-12-21T04:35:44Z"
    generation: 1
    name: grafana
    namespace: monitoring
    resourceVersion: "20587"
    uid: f5978d71-a467-4633-b359-4c94d83937ea
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`grafana.apps.house.simonellistonball.com`)
      services:
      - name: prometheus-grafana
        port: 80
    tls:
      secretName: monitoring-tls
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"prometheus","namespace":"monitoring"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`prometheus.apps.house.simonellistonball.com`)","services":[{"name":"prometheus-kube-prometheus-prometheus","port":9090}]}],"tls":{"secretName":"monitoring-tls"}}}
    creationTimestamp: "2025-12-21T04:35:44Z"
    generation: 1
    name: prometheus
    namespace: monitoring
    resourceVersion: "20590"
    uid: ec437d39-666e-47a2-bacc-fe6e2cc8b770
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`prometheus.apps.house.simonellistonball.com`)
      services:
      - name: prometheus-kube-prometheus-prometheus
        port: 9090
    tls:
      secretName: monitoring-tls
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"n8n","namespace":"n8n"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`n8n.apps.house.simonellistonball.com`)","services":[{"name":"n8n-web","port":5678}]}],"tls":{"secretName":"n8n-tls"}}}
    creationTimestamp: "2025-12-22T11:04:55Z"
    generation: 2
    name: n8n
    namespace: n8n
    resourceVersion: "356430"
    uid: 754029d6-66c9-4465-b0a9-18bd50dad17c
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`n8n.apps.house.simonellistonball.com`)
      services:
      - name: n8n-web
        port: 5678
    tls:
      secretName: n8n-tls
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"redpanda-console","namespace":"redpanda"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`redpanda.apps.house.simonellistonball.com`)","services":[{"name":"redpanda-console","port":8080}]}],"tls":{"secretName":"redpanda-console-tls"}}}
    creationTimestamp: "2025-12-22T13:08:43Z"
    generation: 2
    name: redpanda-console
    namespace: redpanda
    resourceVersion: "151339"
    uid: 7ed21f58-317a-4948-93ad-123ed3c4069b
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`redpanda.apps.house.simonellistonball.com`)
      services:
      - name: redpanda-console
        port: 8080
    tls:
      secretName: redpanda-console-tls
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"traefik-dashboard","namespace":"traefik"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`traefik.apps.house.simonellistonball.com`) \u0026\u0026 (PathPrefix(`/dashboard`) || PathPrefix(`/api`))","services":[{"kind":"TraefikService","name":"api@internal"}]}],"tls":{"secretName":"apps-house-tls"}}}
    creationTimestamp: "2025-12-21T03:32:04Z"
    generation: 1
    name: traefik-dashboard
    namespace: traefik
    resourceVersion: "15807"
    uid: 47c6fdc6-5800-466d-9d3c-899aef2322e6
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`traefik.apps.house.simonellistonball.com`) && (PathPrefix(`/dashboard`)
        || PathPrefix(`/api`))
      services:
      - kind: TraefikService
        name: api@internal
    tls:
      secretName: apps-house-tls
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"whisper","namespace":"whisper"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`whisper.apps.house.simonellistonball.com`)","services":[{"name":"whisper","port":8000}]}],"tls":{"secretName":"whisper-tls"}}}
    creationTimestamp: "2025-12-22T22:10:33Z"
    generation: 5
    name: whisper
    namespace: whisper
    resourceVersion: "221577"
    uid: 178e77d2-f881-40d5-9f0b-dcfe7e9187bc
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`whisper.apps.house.simonellistonball.com`)
      services:
      - name: whisper
        port: 8000
    tls:
      secretName: whisper-tls
kind: List
metadata:
  resourceVersion: ""
