apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whisper
  namespace: whisper
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`whisper.apps.house.simonellistonball.com`)
      services:
        - name: whisper
          port: 8000
  tls:
    secretName: whisper-tls
