apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webhook-relay
  namespace: webhook-relay
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`webhook-relay.apps.house.simonellistonball.com`)
      services:
        - name: webhook-relay
          port: 8080
  tls:
    secretName: webhook-relay-tls
